### ISSUE TITLE
Date Incorrect By A Day

### ISSUE THREAD

**Issue by radikal9** [alvarobartt/investpy#109]
I realize this is similar to a closed issue but it still seems to be broken. 
Located in the US on EST. Using the code:

import investpy
df = investpy.get_stock_historical_data(stock='C',
                                        country='united states',
                                        from_date='01/01/2010',
                                        to_date='26/02/2020')
print(df)

The date is off by 1 day - see screen grab where Feb 26 data on investor.com is showing as Feb 25 data using the code. The link to the screen grab is https://drive.google.com/open?id=1hXDMiU1f_6dsau7DZcCTdwI1Zhszj9pk

**Comment by alvarob96** [comment]
Hi @radikal9! Thank you for reporting this issue, I tried to simulate the same request as you and it works perfectly for me... 

So I am guessing that it may be because of you local timezone or something like that but if you are able to see the data in Investing.com without any VPN connection I guess that `investpy` functionality should work without problems.

![issue109](https://user-images.githubusercontent.com/36760800/75465482-ff304800-5988-11ea-8d67-4603f3930d4a.png)

I will close this issue for now, just let me know if you have any other problems or if you find the root of the problem.

**Comment by radikal9** [comment]
Thanks. Gives me an idea. I do have a VPN - I will set it to Europe and run the code and then set it to local EST and run it again and see what happens. This will help us narrow down the (potential) issue.

**Comment by eisimoes** [comment]
The classmethod "datetime.fromtimestamp()" with the optional argument "tz" as "None" (default) converts the timestamp to the platform’s local date and time.

As the investing.com's timestamps are generated with the hour and minute paramethers setted as 0, the reported problem will only if the machine local's timezone offset is negative (UTC -XX:00).

For example, if the machine local's timezone is UTC-4 (America/New_York), the returned value for timestamp 1588291200 (2020-05-01 00:00) will be "datetime.datetime(2020, 4, 30, 20, 0)". But, if the local's timezone is UTC+2 (Europe/Madrid), the returned value will be "datetime.datetime(2020, 5, 1, 2, 0)".

The solution to this issue is to pass the correct paramether to the classmethod "datetime.fromtimestamp()".

Example:

_**import pytz**
...
stock_date = datetime.strptime(str(datetime.fromtimestamp(int(info[0]), **tz=pytz.utc**).date()), '%Y-%m-%d')
..._

**Comment by radikal9** [comment]
@eisimoes Brilliant figuring it out! I had tried with a VPN from Madrid but got the same results and just kinda gave up that a solution would be found. Never thought it would be the time on my local machine! So in the sample code:

import investpy
df = investpy.get_stock_historical_data(stock='C',
country='united states',
from_date='01/01/2010',
to_date='26/02/2020')
print(df)

Where would one add in your code to fix the problem?

**Comment by alvarobartt** [comment]
Hi @radikal9, thank @eisimoes for reporting the real problem!

He opened an issue #151 so as to present the solution to the mentioned problem. I will be fixing it today or tomorrow, as long as I find time. Anyway, make sure to subscribe to the issue #151 so as to keep up with the latest updates.

Thanks a lot @eisimoes!

**Comment by radikal9** [comment]
Thanks! I will subscribe to it. Appreciate what you have done with the project BTW.

**Comment by alvarobartt** [comment]
Hi @radikal9, this issue has been properly solved as @eisimoes proposed. So thank you both for reporting and solving the issue, respectively.

__Note that currently it is just available on the developer version__ which you can install with the following command:
```
pip install git+https://github.com/alvarobartt/investpy.git@developer
```

__Thank you! Remember to star the repo if you found it useful and follow me at GitHub so as to get notified of all the updates!__
