### ISSUE TITLE
LSE: Historical Data Testing 

### ISSUE THREAD

**Issue by lefig** [alvarobartt/investpy#115]
Hi there,

I have been performing some LSE equity data downloading testing but  have experienced some errors. The API call .get_stock_historical_data returns a not found exception for the following symbols. I have attached a test file. Please see bellow.

This issue follows on from the previous issue (I have installed the latest version of investpy).

The symbols are located by the search API functions but the download fails.

Thanks in advance

Fig
[failed_investing_symbols.txt](https://github.com/alvarob96/investpy/files/4289604/failed_investing_symbols.txt)

**Comment by lefig** [comment]
If you need any further information, please feel free to ask.

Thank you

Fig

**Comment by lefig** [comment]
Please find attached the universe that I use for trading. There are 481 items all listed in the UK (LSE). They are located fine using the search API. But there are many that I am unable to download history data for (see above). The file may help your diagnostics. That would be great.

[universe.txt](https://github.com/alvarob96/investpy/files/4294286/universe.txt)

**Comment by lefig** [comment]
Just to add that you are doing fabulous work there. I would offer to help but I don't know python.

**Comment by alvarobartt** [comment]
Thank you for reporting the issue @lefig! I tried to retrieved the stocks you provided in your universe (which I previously transformed into a CSV file), but name search was throwing some not found errors since Investing.com does not recognize that `Ltd` is the same as `Limited`, and so much more. So I tried to search them by symbol, but a lot search results were found and it was not that easy to filter them, so as described in the image below, all the symbols are available in Investing.com, but as reported in issue #, `investpy.search()` function still needs to be improved.

**Comment by lefig** [comment]
That is fabulous news and thank you too.
I will still continue the testing.
Investing.com is indeed strange and frequently when searching initially no symbols are returned but with a little experimentation a search can in fact yield some symbols...

Thank again:)
