### ISSUE TITLE
Missing Stock counter in Malaysia

### ISSUE THREAD

**Issue by sea98745** [alvarobartt/investpy#117]
Hi there,

Found that the investpy is only has 929 stocks in the stock.csv file , where the investing.com show it has 932 entry when screen for Malaysia stocks
![image](https://user-images.githubusercontent.com/19601470/76131281-d83cda80-6048-11ea-9e3c-e0d16c75e5c0.png)
![Untitled](https://user-images.githubusercontent.com/19601470/76131330-028e9800-6049-11ea-88bb-8c07da06d3ac.jpg)

**Comment by alvarobartt** [comment]
Thank you for reporting the issue @sea98745! I will fix that as soon as possible since I need to launch again the script to automatically download all static data from Investing.com, I will check that the Investing.com product counters match the retrieved data. If anything goes wrong, data will be updated next week when **investpy**'s 1.0 version is out.

**Comment by sea98745** [comment]
Hi alvarobartt,

I still  malaysia stock only has 929 entries. May I know when it will upgrade this ?
