### ISSUE TITLE
Historical prices of BGIc1.

### ISSUE THREAD

**Issue by mreismendes** [alvarobartt/investpy#120]
Hi there!

Is it possible to retrieve data from the contract BGIc1? It's a Brazilian Live Cattle Contract (Futures), available on https://www.investing.com/commodities/live-cattle?cid=964528.

So far I've tried the commodities API unsuccessfully.

Investpy is superb, thank you for the work.

**Comment by alvarobartt** [comment]
Hi @mreismendes, thank you for reporting this issue! Since the `Live Cattle Contract`'s main stock exchange is the United States, the Brazilian commodity is not indexed among **investpy**'s static data as you can see below in the function `investpy.search_commodities()` results. Anyways, you can use the `investpy.search(text, filters, n_results)` function in order to search Investing.com products using its search engine, which is as easy as it is presented below.

![image](https://user-images.githubusercontent.com/36760800/76699952-9ba95880-66b2-11ea-8c4e-ccea42fcd38f.png)

The documentation and usage over `investpy.search(text, filters, n_results)` is intended to be done before the **investpy**'s 1.0 release comes out, so its usage may vary, but the presented usage above is stable for current latest investpy version. Thank you again! Any further doubt or problem feel free to open an issue.

**Comment by mreismendes** [comment]
Thank you for the advice!
