### ISSUE TITLE
Rate limiting / blocking / caching

### ISSUE THREAD

**Issue by ymyke** [alvarobartt/investpy#126]
Hi, thanks for the package!

Did you ever have any issues with rate limiting and/or blocking by investing.com? 

In what ways can I configure investpy to be as friendly as possible to investing.com?

One thing I could do is `import requests_cache` alongside investpy so investpy's requests get cached automatically, correct?

Thanks again!
myke.

**Comment by alvarobartt** [comment]
Hi @ymyke, thank you for your contribution. Just give me some days to find out if any of those concepts fit investpy functionality since Investing.com does not have any limit when it comes to data retrieval.

Currently I can tell you that caching will not be suitable for recent/historical data retrieval since Investing.com updates the last known value real time and the same request may differ since the last known value is different. Anyways, **maybe implementing a cache may work when retrieving data in off-days** such as weekends or holidays whenever the market is closed.

I will consider it, thank you again!

**Comment by ymyke** [comment]
Of course, if you need "real-time" information you can't use caching.

However, apps that mostly need historical data (my use case) could use caching to prevent hitting investing.com over and over again with the same request.

I suggest you look into requests_cache to see whether it works properly with your package and then offer that as a recommnedation to your community.
