### ISSUE TITLE
Retrieve Germany and other countries Manufacturing Purchasing Managers Index (PMI)

### ISSUE THREAD

**Issue by ansobe** [alvarobartt/investpy#136]
Been trying to scrape pmi index data from "https://www.investing.com/economic-calendar/more-history" using requests.post with the request headers and the form data seen with the inspection tool from my internet browser. The most I have been able to get, though, is either a 404 response or a 403 playing a little bit with the the headers.I am only a begginer. I was wondering, if the feature could be added to investpy. Thanks for the amazing work, and making it aveliable for everyone.

**Comment by alvarobartt** [comment]
Hi @ansobe, first of all sorry for taking too long to answer and thank you for opening this issue! As you may know, there is an investpy function available, which is called `investpy.get_calendar()` which retrieves the Economic Calendar according to the specify parameters. In order to know how to use the function, please check: https://github.com/alvarobartt/investpy/blob/8d5d12fe02a4fa68bd755c0191adfc82c3f91ac6/investpy/news.py#L20

__Note that currently it is just available on the developer version__ which you can install with the following command:
```
pip install git+https://github.com/alvarobartt/investpy.git@developer
```

__Thank you! Remember to star the repo if you found it useful and follow me at GitHub so as to get notified of all the updates!__

**Comment by ansobe** [comment]
Great! Thank you so much. I was able to scrape the data with selenium but it takes forever to go over all the data for every PMI index. Investpy is a much cleaner and elegant solution!!

**Comment by dss010101** [comment]
what parameters would you pass to retrieve all the data say from this page: https://www.investing.com/economic-calendar/chicago-pmi-38?
