### ISSUE TITLE
get_stock_information bug

### ISSUE THREAD

**Issue by ma73es** [alvarobartt/investpy#142]
get_stock_information seems to fail for some countries. For example:

import invetspy
investpy.get_stock_information('AAV','canada')

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-ce1ee277333a> in <module>()
----> 1 investpy.get_stock_information('AAV','canada')

1 frames
/usr/local/lib/python3.6/dist-packages/investpy/stocks.py in get_stock_information(stock, country, as_json)
   1054     stock = stock.strip()
   1055 
-> 1056     if unidecode.unidecode(stock.lower()) not in [unidecode.unidecode(value.lower()) for value in stocks['symbol'].tolist()]:
   1057         raise RuntimeError("ERR#0018: stock " + stock.lower() + " not found, check if it is correct.")
   1058 

/usr/local/lib/python3.6/dist-packages/investpy/stocks.py in <listcomp>(.0)
   1054     stock = stock.strip()
   1055 
-> 1056     if unidecode.unidecode(stock.lower()) not in [unidecode.unidecode(value.lower()) for value in stocks['symbol'].tolist()]:
   1057         raise RuntimeError("ERR#0018: stock " + stock.lower() + " not found, check if it is correct.")
   1058 

AttributeError: 'float' object has no attribute 'lower'

**Comment by alvarobartt** [comment]
Hi @ma73es, thank you for reporting this error. I have already checked it, and it is due to the **investpy's static data which needs an update** as already reported in #134, since **some information has been updated in Investing.com**. Anyway, I found out that the erroring stock is the one presented below, which has no symbol among investpy's static data, but indeed it does have a symbol in Investing.com (which is NA).

![image](https://user-images.githubusercontent.com/36760800/78713073-f16fca00-7919-11ea-9fd9-3051e9ee17db.png)

Thank you! I will fix this ASAP.
