### ISSUE TITLE
Incorrect date when the timezone offset is negative

### ISSUE THREAD

**Issue by eisimoes** [alvarobartt/investpy#151]
This issue was already repoted on https://github.com/alvarobartt/investpy/issues/95 and https://github.com/alvarobartt/investpy/issues/109.

The classmethod "datetime.fromtimestamp()" with the optional argument "tz" as "None" (default) converts the timestamp to the platform’s local date and time.

As the investing.com's timestamps are generated with the hour and minute paramethers setted as 0, the reported problem will only if the machine local's timezone offset is negative (UTC -XX:00).

For example, if the machine local's timezone is UTC-4 (America/New_York), the returned value for timestamp 1588291200 (2020-05-01 00:00) will be "datetime.datetime(2020, 4, 30, 20, 0)". But, if the local's timezone is UTC+2 (Europe/Madrid), the returned value will be "datetime.datetime(2020, 5, 1, 2, 0)".

The solution to this issue is to pass the correct paramether to the classmethod "datetime.fromtimestamp()".

Example:

import pytz
...
stock_date = datetime.strptime(str(datetime.fromtimestamp(int(info[0]), tz=pytz.utc).date()), '%Y-%m-%d')
...

**Comment by alvarobartt** [comment]
Thanks a lot @eisimoes!

Anyway, I kind of solved the error as you can see in the file https://github.com/alvarobartt/investpy/blob/developer/investpy/news.py, from the developer branch as reported in the commit message https://github.com/alvarobartt/investpy/commit/c40ff4d26988b40b5f09bb74a470c60eeb5b1d0e

The error I found it was that the timezone when retrieving economic calendars was being calculated wrong, since as you mentioned, the ones with a negative offset were not being properly calculated, since I test the package from Spain and it worked perfectly, since our summer timezone is GMT+2.

Also, if you think that it can be improved, feel free to create a Pull Request solving the issue or improving this timezone calculation.

Thanks a lot again @eisimoes!

**Comment by alvarobartt** [comment]
Hi @eisimoes, I re-opened this issue since I guess that the date error involves every data retrieval function while parsing the date retrieved from Investing.com. I am not completely sure, so could you please confirm me that the related issue needs to be applied to all data retrieval functions?

Sorry, but in the previous message I confused this issue with the one related to a bad timezone calculation I was doing while retrieving the stock calendar. Anyway, give me all the related info and I will try to solve it as soon as possible.

**Comment by alvarobartt** [comment]
Hi again @eisimoes! Thanks a lot for proposing the issue solving and contributing to its fix. Also, thank you for the detailed explanation and sorry for the spam of GitHub messages that you may have found on your inbox.

__Note that currently it is just available on the developer version__ which you can install with the following command:
```
pip install git+https://github.com/alvarobartt/investpy.git@developer
```

__Thank you! Remember to star the repo if you found it useful and follow me at GitHub so as to get notified of all the updates!__

**Comment by eisimoes** [comment]
Thank you for the update.
