### ISSUE TITLE
Update stock.csv listing

### ISSUE THREAD

**Issue by unforgiven1990** [alvarobartt/investpy#152]
Hey Alvarobartt,

First of all, very useful library, appreciated!

I would like to update all stock, indices, ETFs list frequently to check which assets have been recently released in the market.

After checking the doc and the code, I found that these tickers are stored in multiple .csv formatted files during the installation of investpy. 

How do I frequently update the listing? Is there a callable function or do I have to uninstall and install investpy just to get the latest listing?

Thank you!

Best
CJ

**Comment by alvarobartt** [comment]
Hi @unforgiven1990, thank you for your kind words and support!

As you mentioned, those listings (CSV files) are static, but updated once a month with a cronjob.

Anyway, I just upload the updated version whenever a new investpy release is out, since I am searching for a stable server to host the files, so that the update frequency is a week or less and users can just download the updated files from an investpy function, just like a lot other packages do. I will update those files really soon, and will be available on the development version which is stable.

Please stay tuned, thank you for your support and patience!

**Comment by unforgiven1990** [comment]
Hey @ alvarobartt,

Thanks for your fast response. Sounds very awesome. I can’t wait for the new update!

Cheers

**Comment by lkangas** [comment]
Any news on this? Stocks.csv looks like 10 months old and is missing lots of new stocks.

I also found some funds that changed names a while back and updates don't end up to the static lists.

**Comment by alvarobartt** [comment]
Hi @lkangas, I need to pay for a server so as to run the script that generates those files, as it takes some time due to the Investing.com limitations, so you will need to wait a little bit more... Sorry! 👍🏻 

Anyway, in the meantime, you can use the `investpy.search_quotes()` functionality that lets you use the Investing.com search engine so as to retrieve all the information indexed in Investing.com even though that information is not included in the CSV files 😄 Read more about this functionality at https://github.com/alvarobartt/investpy/wiki/investpy.search_quotes()

**Comment by lkangas** [comment]
Thanks, I think search_quotes will solve my problems!
