### ISSUE TITLE
few commodity data is not available

### ISSUE THREAD

**Issue by sunilgug** [alvarobartt/investpy#157]
I ran following statement:

df=investpy.get_commodity_historical_data(commodity="NCHK0",country='india',from_date='1/1/2019',to_date='1/1/2020')

it has shown following error:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-18-04105d61b463> in <module>()
----> 1 df=investpy.get_commodity_historical_data(commodity="NCHK0",country='india',from_date='1/1/2019',to_date='1/1/2020')

/usr/local/lib/python3.6/dist-packages/investpy/commodities.py in get_commodity_historical_data(commodity, from_date, to_date, country, as_json, order, interval)
    512 
    513     if unidecode.unidecode(commodity) not in [unidecode.unidecode(value.lower()) for value in commodities['name'].tolist()]:
--> 514         raise RuntimeError("ERR#0079: commodity " + commodity + " not found, check if it is correct.")
    515 
    516     if country is None:

RuntimeError: ERR#0079: commodity nchk0 not found, check if it is correct.

**Comment by alvarobartt** [comment]
Hi @sunilgug, currently there is some Investing.com data that is not available in investpy, since the indexing of the data on the web is sometimes bad formatted and some data can not be accessed. 

Please, subscribe to #134 so as to get notified whenever a static file is updated until the stable release comes out.

Anyway, you can easily retrieve the missing data (which means that it is not indexed among the static files of investpy, but indeed it is available at Investing.com), using the following function: `investpy.search_quotes()` from the developer version. An example is provided below:

```python3
import investpy

search_results = investpy.search_quotes(text='NCHK0',
                                        countries=['india'],
                                        products=['commodities'],
                                        n_results=1)

data = search_results[0].retrieve_historical_data(from_date='1/1/2019',
                                                  to_date='1/1/2020')

print(data.head())
```

```{r, engine='python', count_lines}
              Open    High     Low   Close
Date                                      
2019-01-01  4334.0  4344.0  4293.0  4309.0
2019-01-02  4304.0  4329.0  4250.0  4271.0
2019-01-03  4239.0  4320.0  4235.0  4310.0
2019-01-04  4286.0  4291.0  4222.0  4277.0
2019-01-07  4242.0  4260.0  4198.0  4213.0
```

__Note that currently it is just available on the developer version__ which you can install with the following command:
```
pip install git+https://github.com/alvarobartt/investpy.git@developer
```

__Thank you! Remember to star the repo if you found it useful and follow me at GitHub so as to get notified of all the updates!__

**Comment by sunilgug** [comment]
Thanks a lot for the quick response. And providing the temporary solution. I really appreciate it

**Comment by sunilgug** [comment]
The sample code which you shared is working. Will you please help me in the accessing technicals and candlestick pattern details of the instruments from the developer version?

Thanks in advance.

**Comment by alvarobartt** [comment]
Hi @sunilgug, currently the Candlestick Patterns from Investing.com are not included among investpy functions, but you can propose it as a new feature explaining, why should they be included, where can you find them on the Investing.com site, etc. And the technical information can be retrieved with the following functions:

```
import investpy

data = investpy.technical_indicators(name='AAPL', country='United States', product_type='stock')
data = investpy.moving_averages(name='AAPL', country='United States', product_type='stock')
data = investpy.pivot_points(name='AAPL', country='United States', product_type='stock')
```

Thank you! Remember to star the repo if you found it useful and follow me at GitHub so as to get notified of all the updates!
