### ISSUE TITLE
Error generating the timezone in 'news'

### ISSUE THREAD

**Issue by ifscher** [alvarobartt/investpy#162]
Hello,

When the timezone is left empty, it gives KeyError when the calculated timezone returns negative.
The return comes with double minus: KeyError: 'GMT --3:00'

**Comment by alvarobartt** [comment]
Hi @ifscher, thank you again for reporting this issue! As I told you in the previous issue you opened, this issue/bug was supposedly solved in the developer branch, so this error should not happen on the developer version, which you can install with the following command:

```
pip install git+https://github.com/alvarobartt/investpy.git@developer
```

As I told you before, just check it and if it does work just close the issue and if it still errors just tell it to me so that I can work on its solving. Thank you!

__Remember to star the repo if you found it useful and follow me at GitHub so as to get notified of all the updates!__

**Comment by ifscher** [comment]
Did as you said and installed the developer version. Everything is working great! Thank you!
