### ISSUE TITLE
Date format incoherence

### ISSUE THREAD

**Issue by typhoon71** [alvarobartt/investpy#169]
The date format is stated to be dd/mm/yyyy, but I  found that's it's not always true.

When using:
```python
fx = investpy.get_currency_cross_historical_data(currency_cross="EUR/USD", from_date="01/01/2020", to_date="31/06/2020")
```
or
```python
df = investpy.get_etf_historical_data(etf="FUESSV50", country="vietnam", from_date="01/01/2020", to_date="01/06/2020")
```
the date is properly handled (you'll get the values till June 1). 
This happens using another nation too (tested with country="united kingdom"). 

But using:
```python
search = search = [x for x in investpy.search(text="XLVS") if x.country == "united kingdom"]
df = search[0].retrieve_historical_data(from_date="01/01/2020", to_date="01/06/2020")
```
the date is mishandled (you'll get the values till January 6). So the date format would be mm/dd/yyyy instead (using to_date="06/01/2020" does fix the issue).

I can't use investpy.get_etf_historical_data() as a workaround because it relies on a csv archive of etfs, which is not optimal (right now it's not up to date and a bunch of isin/symbols/nations are missing).

 Can this be fixed? Thanks.

**Comment by alvarobartt** [comment]
Hi @typhoon71, thank you for reporting this issue! I will try to work on it during this weekend, since I am pretty busy during week days. I know that the `investpy.get_etf_historical_data()` is not really consistent, but I am working to try to retrieve all the ETFs from Investing.com which may seem an easy task but indeed is not, since the Investing.com listings do not provide all the information easily.

Also, make sure to use the developer version, which will be released as a newer version probably this weekend solving a lot of issues and including a lot of new features, but the updated CSV files will take a little bit longer, so sorry for the inconvenience.

You you can install the developer version with the following command:

```
pip install git+https://github.com/alvarobartt/investpy.git@developer
```

__Thank you! Remember to star the repo if you found it useful and follow me at GitHub so as to get notified of all the updates!__

**Comment by typhoon71** [comment]
I will test the new version for sure.

Btw, I'm not asking you to keep the list of financial instruments updated.
I think the main focus is getting the dataset of some instrument (ex: etf, stock, bond).
One should know basic intrument info: usually you already have isin, ticker, nation, exchange.

Oh, let's not forget the due thanks for this project.

**Comment by alvarobartt** [comment]
Hi @typhoon71 sorry for coming back to this too late, could you please check whether this issue is still happening? Because AFAIK this was already solved, but I want to make sure 😃

To let you know I'm currently preparing the new investpy release so I'm going through all the old issues as some of them are solved but not closed 😩

Thanks a lot!

**Comment by typhoon71** [comment]
I'll check and let you know; indeed it may be fixed already but I want to test my script to be 100% sure.

**Comment by alvarobartt** [comment]
Cool @typhoon71! 👍🏻 Feel free to close the issue if the feedback is positive

**Comment by typhoon71** [comment]
OK, I can confirm the dates are treated correctly, I forgot to close this when they got fixed.
I checked my code and my own workaround is commented out.
Closing as solved.
