### ISSUE TITLE
Wrong data collected ?

### ISSUE THREAD

**Issue by j-bac** [alvarobartt/investpy#170]
Many thanks for this great project !

I am trying to collect ETF data but I have some trouble with [this ETF](https://www.investing.com/etfs/bnp-paribas-easy-sp-500-ucits-historical-data?cid=997096). 

I could not find it in your .csv file, so I collected data in the following way using your package. It seems correct for recent years, but there seems to be an issue around mid 2017 with a huge drop, which is not found on investing.com. Any idea what this is due to ? 

```python
res = investpy.search('BNP Paribas Easy S&P 500 UCITS ETF EUR C (EEESE) ', filters=['etfs'])
data = res[0].retrieve_historical_data('01/01/1900','01/01/2300')
plt.plot((data['Open']+data['Close'])/2)
```

When collecting this [same ETF on yahoo finance](https://finance.yahoo.com/quote/ESE.PA/history?period1=1379289600&period2=1591401600&interval=1mo&filter=history&frequency=1mo), it seems recent years are the same as those collected from investing.com but not older data:

```python
import pandas_datareader
start_date = '1900-01-01'
end_date = '2100-12-31'
panel_data = pandas_datareader.data.DataReader('ESE.PA', 'yahoo')
plt.plot(panel_data['Close'])
plt.plot(data['Close'][545:])
```

Many thanks!

**Comment by alvarobartt** [comment]
Hi @j-bac! First of all, thank you for reporting this issue; you may need to install the developer version until the stable release comes out that is expected to be soon. Installing the developer version means that you will have all the current updates, improvements, etc. before they come out as stable. 

To install the investpy from the developer branch:
```
pip install git+https://github.com/alvarobartt/investpy.git@developer
```

In the question you are asking, the `investpy.search()` function has been renamed to `investpy.search_quotes()` fixing some issues, which may be related to the historical data retrieval, since I am guessing that the problem you are exposing is highly related to the one presented in #135.

Let me know if that worked for you! And if it did work, you can just close this issue by yourself, but I will still wait for your response.

__Thank you! Remember to star the repo if you found it useful and follow me at GitHub so as to get notified of all the updates!__

**Comment by j-bac** [comment]
Thanks for the reply! I tried with search_quotes on the developer version (1.0), but it seems there is still the same issue

**Comment by alvarobartt** [comment]
Then, can you share the function call and its output so that I can test in locally and debug it so as to spot the error? Thank you!

__Note__: to include Python code blocks in any comment use __\```python__ at the start of the block and __\```__ at the end.

**Comment by j-bac** [comment]
res = investpy.search('BNP Paribas Easy S&P 500 UCITS ETF EUR C (EEESE) ', filters=['etfs'])
data = res[0].retrieve_historical_data('01/01/1900','01/01/2300')
plt.plot(data['Close'])

The data and output plot show a very strong dip which is not seen on the investing.com website for  [this ETF](https://www.investing.com/etfs/bnp-paribas-easy-sp-500-ucits-historical-data?cid=997096)

**Comment by alvarobartt** [comment]
Thank you for reporting it @j-bac! I will test it later today and let you know.

**Comment by DnZmfr** [comment]
Actually the drop (-91%) is also visible on investing.com 

`Mar 09, 2017 | 9.90 | 9.90 | 9.93 | 9.88 | 70.80K | -91.70%`

**Comment by j-bac** [comment]
You are correct, my bad I didn't look at daily values but monthly values
