### ISSUE TITLE
Ticker function missing

### ISSUE THREAD

**Issue by antamosan** [alvarobartt/investpy#171]
I can't find the ticker function.

High an low plus open and close is not enough information for day trading. You need the ability to get the real time value (ticker) in order to program an alert, for example.

Regards.

**Comment by alvarobartt** [comment]
Hi @antamosan! Thank you for proposing this enhancement! Currently, when retrieving either recent or historical data from any financial product, if the request is made while the market is open, the close value of the current day you are sending the request is the current value on the exact moment you are sending it.

__If the market is still open, the close value of the current day corresponds to the actual value, since the market has not been closed yet.__ 

Also, if you can find this feature on Investing.com and the one you request differs from the solution I am providing to you, just let me know, and send me the Investing.com link from where all that information can be retrieved and I will implement it in investpy as soon as possible. 

__Thank you! Remember to star the repo if you found it useful and follow me at GitHub so as to get notified of all the updates!__

**Comment by antamosan** [comment]
Hi @alvarobartt.

Thank you for your response. I tested your tool yesterday (with markets closed) so I didn't think it would work in that way. I was able to program an external ticker with bs4, but I am still not well versed in this tool so my solution is likely slower than yours.

Anyway I recommend programming an specific function for ticker (which more likely you already have, only an "alias" is required) as it would be more natural for the final user.

Regards.

**Comment by alvarobartt** [comment]
Hi @antamosan, I am glad that it was useful to you! Anyway, you mean to include a function just to retrieve the current financial product's value? Like just the current closing value if the market is open? If you mean to propose that, please open another issue requesting the addition of that functionality, explaining it a little bit just like you did above.

__Thank you! Remember to star the repo if you found it useful and follow me at GitHub so as to get notified of all the updates!__
