### ISSUE TITLE
Investing.com website down?

### ISSUE THREAD

**Issue by lefig** [alvarobartt/investpy#175]
Hi there,

For the past two days we have been unable to access the website using the API.

There is a generic error from the HTTP server:
406 Not Acceptable

Has anyone else experienced this problem?

Thanks

Fig

**Comment by alvarobartt** [comment]
Hi @lefig, no, Investing.com is not down. The HTTP error 406 appears whenever you make too many requests to any Investing.com Stocks/Equities section, since some weeks ago we found out that Investing.com sets a limit quota but just over Stocks. You can find more information at #149 on how to avoid it as reported by other users, since as long as it is an Investing.com issue I can not do anything about it.
