### ISSUE TITLE
Investing.com web site down?

### ISSUE THREAD

**Issue by lefig** [alvarobartt/investpy#176]
Hi,

Is anyone else experiencing difficulty accessing investing.com symbol data using either the API or simply a browser?

We receive generic http error at present: 

406 Not Acceptable

This has been for the last 3 days now.

Thank you

Fig

**Comment by lefig** [comment]
By way of update...

Investing confirmed the IP address is blocked now and suggested using a VPN. Beware of this.

The problem is not due to overuse as we use sleep calls but probably due to their proxy rules.

I would suggest you implement a headerless browser like call using an agent to abide by those rules.

Until then we will not be able to use investpy anymore as we are unwilling to use a VPN.

**Comment by alvarobartt** [comment]
Hi @lefig. thank you for reporting it and sorry for taking too long to answer I've been mad busy lately!

As you mention, Investing.com seems to have an IP Blacklist regarding the Stocks data which will end up in your IP being blacklisted when sending too much requests to that data. As you suggest, every request is being sent using a random User-Agent from a list of valid User-Agents, so the main problem is related to Investing.com not to investpy...

Anyway, as we already discussed, if you know any solution that you think should work you can either propose it or develop it yourself and then create a Pull Request!

Thank you!

P.S.: Closing this issue even though we know this is still an unsolved problem, but we cannot do anything about it since it is currently on Investing.com's side.
