### ISSUE TITLE
Pandas Dataframe reads in symbol 'NA' as float nan

### ISSUE THREAD

**Issue by mplumb80** [alvarobartt/investpy#180]
Crashes when attempting to run get_stock_historical_data() on a canadian stock.  The stock National Bank has symbol NA which pandas interprets as a float.

crashes on line 511 of stocks.py attempting to cast symbol to lowercase using .lower().

I fixed it by overriding what Pandas considers to be nan by changing line 496 to be:
stocks = pd.read_csv(pkg_resources.resource_filename(resource_package, resource_path), keep_default_na=False, na_values=['_'])

**Comment by alvarobartt** [comment]
Hi @mplumb80, thanks for reporting this! I was going through old issues, and just to let you know that this was already solved some releases ago :hugs:

The fix I did was `stocks = pd.read_csv(pkg_resources.resource_filename(resource_package, resource_path), keep_default_na=False)`, instead of including also the `na_values=['_']` as you suggest. I also ran a couple of tests a while ago, but can you please check whether this is working fine for you or not?

Thanks again and sorry for taking so long to answer this issue! :+1:
