### ISSUE TITLE
Possible fix of "ERR#0015: error 406, try again later.". I need your opinion on this!

### ISSUE THREAD

**Issue by alvarobartt** [alvarobartt/investpy#191]
Hi everyone,

as it has been reported by many users, Investing.com seems to have a strong limitation on the requests sent towards any type of Stock data. A possible fix which has been proposed is to use a 1sec timeout between each request so as to avoid those limitations which may include your IP in a Blacklist for a period of +3 days.

So on, I need all of you to answer if you prefer me to include that timeout in the source code of every affected function or that you just prefer to keep it like it is and implement the timeout by yourselves.

Note that this feature will affect mainly the users that just send a little amount of request while it will help the ones that send a huge amount of requests.

Thank you! Regards,
Álvaro Bartolomé.

**Comment by ymyke** [comment]
I think I would just leave it as it is and leave the responsibility to whoever uses your lib. And leave it to them to deal with the trouble of being blocked. Maybe add: 1) some prominent recommendations around caching and timeout to the documentation and 2) catch the 406 and add some more explanations to that error condition and how to mitigate in order to prevent affected people from posting issues here in Github.

As an alternative to this approach, you could also implement the 1 second timeout as a default and give people the chance to turn it off if they know what they are doing.

**Comment by markus080402** [comment]
Hi,

Since this is a problem almost everyone runs into it would be good to include the timeout, but make it configurable in case investing.com changes the rate limiting, then it is easy for the user to change from 1 sec to anything else, for example 0.

Also, would be really good to prepare investpy to rotate between proxy IP addresses if the user for example has a list of 10 proxy IP addresses, then investpy could alternate between them.

Thanks and regards,
Markus

**Comment by lefig** [comment]
This is related to my request for proxy support. Believe me they have good ways to detect and block IP addresses. Their support are friendly btw. And mentioned this.

Anyhow, back to your question... we already put a random sleep request before calling the API. I think that you should leave this to end users to make that call.

**Comment by alvarobartt** [comment]
Ok guys thank you for your help! @ymyke, @markus080402 and @lefig, I will just include some notes in the Documentation page so as to let the users know that they need to include a timeout if they are planning to send a huge amount of requests to investpy.stocks.

Anyway, the Proxy may be included in the 1.1 release once the 1.0 release is out and all the current bugs are fixed!

You can already install the investpy 1.0 version as usual, with ``pip install investpy==1.0`` or ``pip install investpy -U``.

Thank you all!
