### ISSUE TITLE
issue about canada stock

### ISSUE THREAD

**Issue by wenny0501** [alvarobartt/investpy#198]
Hi, alvarobartt,
thanks for your work.
I try to use investpy to scrape canada stock historical data from investing.com.
I tried:
stock='BBVA', country='spain'
stock='IBM', country='united states'
......
investpy works well.
but to all canada stock, there is an error.
I verify the symbol in stocks.csv.
![investpy](https://user-images.githubusercontent.com/68882045/89724882-ac969580-d9d6-11ea-8b82-2423594768a8.PNG)

Question 2: there are many stock are not on the list in stocks.csv. Could I maintain it? How could I get the necessary information to appent?

**Comment by guberm** [comment]
@wenny0501 please try the solution for my bug, I think it will help you #https://github.com/alvarobartt/investpy/issues/346

**Comment by alvarobartt** [comment]
Hi @wenny0501, thanks for reporting this issue!

This was already solved in one of the latest `investpy` releases, so please update your version to the latest one (which currently is `investpy v1.0.6`) :fire: That will solve the issue regarding the Canadian stocks due to a `pandas` issue, as it sets 'NA' as the default NaN value if you don't specify that the conversion from 'NA' to `np.nan` is not needed!

Regarding your second question, currently, I'm looking for the best way to either share the CSV generation scripts or a way to automatically update them let's say once a week or so, but it's not that straightforward... I may remove the static CSV files so that all the functions use the `search_quotes()` functionality internally in order to avoid these issues! But as I told you it's not clear yet...

Anyway, I'm working towards buying a server or a couple of them to generate the static CSV files, but it may not be made before summer... So sorry for that! In the meantime you can use `investpy.search_quotes()` to use the Investing.com search engine and have access to all the financial products available at Investing.com.

More information available at [investpy - search_quotes](https://github.com/alvarobartt/investpy/wiki/investpy.search_quotes()) :+1:

**Comment by alvarobartt** [comment]
Also, feel free to try this script I just created for the Canadian stock you sent me!

```python
import investpy

search_result = investpy.search_quotes(text='AD', products=['stocks'], countries=['canada'], n_results=1)

recent_data = search_result.retrieve_recent_data()
historical_data = search_result.retrieve_historical_data(from_date='01/01/2020', to_date='01/01/2021')
information = search_result.retrieve_information()
```
