### ISSUE TITLE
get_stock_financial_summary gives ValueError

### ISSUE THREAD

**Issue by Swopper050** [alvarobartt/investpy#201]
Hi, thanks for the package, it is awesome!

I was trying to retrieve the financial summary of "TSLA" in "united states", but this yielded a ValueError. As far as I can tell, it tries to make an int from a float string (I'm using investpy 1.0):

<img width="1054" alt="Screenshot 2020-08-09 at 19 34 42" src="https://user-images.githubusercontent.com/38559175/89738240-6a716080-da77-11ea-9193-3b699ed35386.png">

**Comment by MatthieuH5565** [comment]
Does anyone have a fix for this?

**Comment by shigerufw** [comment]
into your folder that you installed investpy

change this =>data[curr_row].append(int(row.text_content().strip()))

into this => data[curr_row].append(float(row.text_content().strip()))

**Comment by alvarobartt** [comment]
Hi @Swopper050, @MatthieuH5565 and @shigerufw, thank you for reporting this issue!

This was already solved in https://github.com/alvarobartt/investpy/pull/205, in order to update investpy from source please use the following command:

``
pip install git+https://github.com/alvarobartt/investpy.git@master
``

Remember to star the repo, follow me here and on Twitter at https://twitter.com/alvarobartt so as to get notified from all the updates and projects I'm working on! ⭐ :octocat:
