### ISSUE TITLE
country == world and euro zone not working

### ISSUE THREAD

**Issue by davins90** [alvarobartt/investpy#208]
Hi all,

i've made a web app on streamlit deployed on Heroku. While i'm downloading country like italu, spain,ecc... the "get_index_recent_data()" function works, but for country like "world" and "euro zone" in local works, but in deploying is not working, warning that " euro zone/word" is not recognized.

Thanks

**Comment by davins90** [comment]
![image](https://user-images.githubusercontent.com/31472994/91443223-526d4f80-e873-11ea-8e38-a6fccb578727.png)

**Comment by IgorCavaca** [comment]
Solution:

go to C:\Users\...\Anaconda3\Lib\site-packages\investpy\utils\constant.py

add {'country': 'world', 'country_name': 'world'} in the variable (INDEX_COUNTRIES).

It's done, you can use the base functions.

**Comment by davins90** [comment]
thank you very much Igor! :)

**Comment by alvarobartt** [comment]
Hi @davins90 and @IgorCavaca! 🤗 

Thank you both for contributing! It's nice to see how you help each other. Sorry for taking so long to answer, but this issue has already been solved by @se-jaeger in https://github.com/alvarobartt/investpy/pull/217, so in order to update investpy so that you have all the latest features, please install it using the following command and everything should be fixed:

```bash
pip install git+https://github.com/alvarobartt/investpy.git@master
```

Just let me know! Remember to star the repo, follow me here and on Twitter at https://twitter.com/alvarobartt so as to get notified from all the updates and projects I'm working on! ⭐ :octocat:

**Comment by alvarobartt** [comment]
@davins90 @IgorCavaca Sorry for taking so long to solve this issue even though it was easy to fix but I though it was already fixed 😩 Now both "world" and "euro zone" data retrieval is available!

To install the latest version with this bug fix as well as some other fixes, please install it as it follows:

```
pip install investpy==1.0.3
```

Remember to star the repository, follow me here at https://github.com/alvarobartt and on Twitter at https://twitter.com/alvarobartt so as to get notified about all the updates and projects I'm working on! :star: :octocat:

**Comment by alvarobartt** [comment]
BTW @davins90 I'd love to see that Streamlit UI 👍🏻 Feel free to create a PR so as to include the project you created using investpy in the following section of the README: https://github.com/alvarobartt/investpy#related-projects

It's as easy as forking the repository, including a couple of lines describing your project in the section "Related projects" and then create a PR so as to merge your fork into the master branch of investpy! 🔥
