### ISSUE TITLE
Can't import indices like MSCI World and other world/global indices

### ISSUE THREAD

**Issue by aktherpu** [alvarobartt/investpy#210]
![image](https://user-images.githubusercontent.com/63063396/92075710-e17de880-edda-11ea-853f-acf8fc58343c.png)
![image](https://user-images.githubusercontent.com/63063396/92075774-07a38880-eddb-11ea-9964-5d1e3940dd65.png)

**Comment by elocke-abroaden** [comment]
I'm also getting this error. I pulled up the DF of the indices and filtered down to a random global one and was unable to retrieve the code, getting error 0034: "country world not found, check if it is correct.'

![image](https://user-images.githubusercontent.com/45102921/92247146-15ced300-eec7-11ea-9d35-c7b7a0f71be7.png)

**Comment by LuisSousaSilva** [comment]
Solution here: https://github.com/alvarobartt/investpy/issues/208

**Comment by alvarobartt** [comment]
Hi @aktherpu, @elocke-abroaden and @LuisSousaSilva! 🤗 

Thank you all for contributing! It's nice to see how you help each other.

Sorry for taking so long to answer, but this issue has already been solved by @se-jaeger in https://github.com/alvarobartt/investpy/pull/217, so in order to update investpy so that you have all the latest features, please install it using the following command and everything should be fixed:

```bash
pip install git+https://github.com/alvarobartt/investpy.git@master
```

Just let me know! Remember to star the repo, follow me here and on Twitter at https://twitter.com/alvarobartt so as to get notified from all the updates and projects I'm working on! ⭐ :octocat:

**Comment by alvarobartt** [comment]
@aktherpu, @elocke-abroaden and @LuisSousaSilva Sorry for taking so long to solve this issue even though it was easy to fix but I though it was already fixed 😩 Now both "world" and "euro zone" data retrieval is available!

To install the latest version with this bug fix as well as some other fixes, please install it as it follows:

```
pip install investpy==1.0.3
```

Remember to star the repository, follow me here at https://github.com/alvarobartt and on Twitter at https://twitter.com/alvarobartt so as to get notified about all the updates and projects I'm working on! :star: :octocat:
