### ISSUE TITLE
stock can be found by search_quotes() by not retrieve_recent_data()

### ISSUE THREAD

**Issue by SBSiuBo** [alvarobartt/investpy#212]
Hi, Thank you so much for developing such great package. I've tried to get the quote for Hong Kong stocks. It can be searched by search_quotes(). However, when calling retrieve_recent_data(), it prompt for an IndexError. Much appreciated for any help. Thank you. 

==============================================
Below is my code:
==============================================
import investpy

stock_code = "0024"
print ("*********" + stock_code + "**********")
search_results = investpy.search.search_quotes(stock_code, products=['stocks'], countries=['Hong Kong'])

for search_result in search_results:
        if (search_result.symbol == stock_code):
                print (search_result)
                data=search_result.retrieve_recent_data()
                print(data)

==============================================
Below is the output
==============================================
*********0024**********
{"id_": 990024, "name": "Burwill Holdings Ltd", "symbol": "0024", "country": "hong kong", "tag": "/equities/burwill-holdings-ltd", "pair_type": "stocks", "exchange": "Hong Kong"}
IndexError!!!! Stock : 0024

**Comment by alvarobartt** [comment]
Hi @SBSiuBo, thanks for the kind words! :fire:

I've just checked the script you sent me as it follows:

```python
import investpy

search_result = investpy.search_quotes(text='0024', products=['stocks'], countries=['hong kong'], n_results=1)

recent_data = search_result.retrieve_recent_data()
historical_data = search_result.retrieve_historical_data(from_date='01/01/2020', to_date='01/01/2021')
information = search_result.retrieve_information()
```

But I'm also running into an `IndexError` exception, so let me further explore this issue so as to identify which is the root of the problem! Thanks for your patience and sorry for the delayed response...

__:pushpin: Make sure that you are using the latest investpy version! `investpy v1.0.6`__

**Comment by alvarobartt** [comment]
P.S. Since the latest `investpy` release you can now set `n_results=1` so that you just receive a single result, which is the first/top result returned by the Investing.com search engine, and, usually, the one you are looking for so that you don't need to loop over the list of results, as you can see in the example above!

**Comment by alvarobartt** [comment]
Ok, @SBSiuBo it seems that there's no "recent" data available at Investing.com as you can see in https://www.investing.com/equities/burwill-holdings-ltd-historical-data, so the issue with the `SearchObj.retrieve_recent_data()` is not with the function itself, but with Investing.com.

I'll include an error message in the next release so that if there's no information available in the `retrieve_recent_data()` method call the error message will suggest the user retrieve the historical data instead of or something similar!

So this stock seems to be inactive right now, I've tested it with:

```python
search_result = investpy.search_quotes(text='0024', products=['stocks'], countries=['hong kong'], n_results=1)

historical_data = search_result.retrieve_historical_data(from_date='01/01/2010', to_date='01/01/2021')
```

And it does work, as it seems to have stopped receiving data in `Aug 16, 2019`.

**Comment by alvarobartt** [comment]
We still need to handle the error whenever either the recent data or the historical data is not available in the selected date range...

**Comment by alvarobartt** [comment]
__Note__ that currently I've just included the same exception trigger whenever the interval search is above 19 years, but for the next release I'll create custom errors so as to provide more information and let the user know whether the error comes from Investing.com or from `investpy` since currently just looking at the exceptions is hard to tell!

**Comment by alvarobartt** [comment]
Hi @SBSiuBo, the new release is already out! :fire:

You can already install it using either ``pip install investpy==1.0.7`` or just update the current version that you are using with ``pip install investpy --upgrade``. Thanks a lot for your support! :+1:

For more information about this new release, you should check [investpy v1.0.7 Release](https://github.com/alvarobartt/investpy/releases/tag/1.0.7) :balloon:
