### ISSUE TITLE
error in function investpy.stocks.get_stock_financial_summary

### ISSUE THREAD

**Issue by evstas87** [alvarobartt/investpy#213]
In case that value is not rounded:
 for example Total Revenue 292.54 I get error ("{ValueError}invalid literal for int() with base 10: ''292.54")

path to data:
https://www.investing.com/equities/alony-hetz-ord1-financial-summary

example:
investpy.stocks.get_stock_financial_summary(stock='ALHE', country='israel',
                                                                                 summary_type='income_statement',
                                                                                 period='quarterly')

**Comment by dennislwm** [comment]
Hi, can I take this one?

**Comment by alvarobartt** [comment]
Hi @evstas87 and @dennislwm, thank you for reporting this issue!

This was already solved in https://github.com/alvarobartt/investpy/pull/205, in order to update investpy from source please use the following command:

``
pip install git+https://github.com/alvarobartt/investpy.git@master
``

Remember to star the repo, follow me here and on Twitter at https://twitter.com/alvarobartt so as to get notified from all the updates and projects I'm working on! ⭐ :octocat:
