### ISSUE TITLE
Invalid literal for int() with base 10: '98.48' get_stock_financial_summary 

### ISSUE THREAD

**Issue by shambekela** [alvarobartt/investpy#219]
Getting an invalid literal for int() with base 10: '98.48' error .

line 1435, in get_stock_financial_summary data[curr_row].append(int(row.text_content().strip()))

![error](https://user-images.githubusercontent.com/12392638/94348897-4d511b00-0040-11eb-96dd-2956d6abb125.PNG)

**Comment by alvarobartt** [comment]
Hi @shambekela, thank you for reporting this issue!

This was already solved in https://github.com/alvarobartt/investpy/pull/205, in order to update investpy from source please use the following command:

``
pip install git+https://github.com/alvarobartt/investpy.git@master
``

Remember to star the repo, follow me here and on Twitter at https://twitter.com/alvarobartt so as to get notified from all the updates and projects I'm working on! ⭐ :octocat:
