### ISSUE TITLE
Unable to get financial summary for Country = Chile

### ISSUE THREAD

**Issue by FranciscoJMB** [alvarobartt/investpy#235]
Hi!

when running this code
data = investpy.get_stock_financial_summary(stock='ANDINAB', country='Chile', summary_type='income_statement', period='annual')

I get the following error:
-> 1435             data[curr_row].append(int(row.text_content().strip()))
ValueError: invalid literal for int() with base 10: '1779025.11'

I guess the string must be converted to float first an then to integer

**Comment by alvarobartt** [comment]
Hi @FranciscoJMB! Thanks for reporting this, this has already been solved in https://github.com/alvarobartt/investpy/pull/205, but as I did not uploaded the new investpy release, that's not available.

In order to fix that until the v1.1 release is out, you can install it using the following command:

```bash
pip install git+https://github.com/alvarobartt/investpy.git@master
```

Just let me know! Remember to star the repo, follow me here and on Twitter at https://twitter.com/alvarobartt so as to get notified from all the updates and projects I'm working on! ⭐ :octocat:

**Comment by nuwandwo** [comment]
@alvarobartt . But for me i get this error , when tried to install. 

ERROR: Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/alvarobartt/investpy.git 'C:\Users\nuwanw\AppData\Local\Temp\pip-req-build-mt72t63c'
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

**Comment by alvarobartt** [comment]
Hi @nuwandwo as you can read on the logs the error is due to a problem with your Git installation (maybe you don't have it installed) please check this: https://git-scm.com/book/en/v2/Getting-Started-Installing-Git Then try the provided solution and let me know 🤗

**Comment by alvarobartt** [comment]
BTW you can also just download this repository as a ZIP file and then with a terminal inside the directory in your local system where the `setup.py` file is placed use this command: ``pip install .``, which will install the latest investpy version from source.
