### ISSUE TITLE
Get Economic Calendar only returns a maximum of 4 days worth of events.

### ISSUE THREAD

**Issue by cheejiayuan512** [alvarobartt/investpy#246]
Hi there,
Firstly I would like to thank you for making this delightful library. It reduces the effort to webscrape for investing data by a ton. However, I can't help but notice that when I use a data range of more than 4 days at a time, it does not return the correct date range. Thank you once again!

**Comment by alvarobartt** [comment]
Hi @cheejiayuan512, thanks for your kind words! 👍🏻 

Could you please provide an example? And share the code you are using so that I can reproduce it myself and solve it?

**Comment by alvarobartt** [comment]
Hi @cheejiayuan512! Could you provide more information regarding this issue? 🤗

**Comment by alvarobartt** [comment]
Hi again @cheejiayuan512, this has been already fixed in the __v1.0.2 investpy release__, which is already out and you can download using the following command:

```
pip install investpy==1.0.2
```

__Note__: a similar issue was reported, you can find more information there! https://github.com/alvarobartt/investpy/issues/186

Remember to star the repository, follow me here and on Twitter at https://twitter.com/alvarobartt so as to get notified from all the updates and projects I'm working on! :star: :octocat:
