### ISSUE TITLE
get_stock_financial_summary crashes on float parsing

### ISSUE THREAD

**Issue by lkangas** [alvarobartt/investpy#259]
Trying
`investpy.stocks.get_stock_financial_summary('REG1V', country='finland')`

crashes in 
`stocks.py, line 1435, in get_stock_financial_summary
    data[curr_row].append(int(row.text_content().strip()))

ValueError: invalid literal for int() with base 10: '49.47'`

Should probably be float?

**Comment by fp-repo** [comment]
I had a similar error with the following call: 
`get_stock_financial_summary(stock='PIRC', country='Italy', summary_type='income_statement', period='quarterly')`

The result is an error in line 1435: "ValueError: invalid literal for int() with base 10: '1277.4'."
I guess the problem is somewhere in the conversion.

**Comment by alvarobartt** [comment]
Thanks for reporting it @fp-repo! Will try to fix this ASAP, `investpy==1.1` needs to be released 🔥

**Comment by alvarobartt** [comment]
Hi @fp-repo! The new investpy release is out! 🔥 To install it please use the following command:

``
pip install investpy --upgrade
``

Remember to star the repo, follow me here and on Twitter at https://twitter.com/alvarobartt so as to get notified from all the updates and projects I'm working on! ⭐ :octocat:
