### ISSUE TITLE
Dates wrong

### ISSUE THREAD

**Issue by manueldiazrod97** [alvarobartt/investpy#282]
Hi bro im a newbie so maybe there is no problem so if there is no an error sorry for the lost of your time .

but for example  this is my code : 
 investpy.get_index_historical_data(index= "S&P/BMV IPC" ,
                                                  country='Mexico',
                                        from_date='01/01/2005',
                                         to_date= '31/12/2020',interval="Monthly")

and  the output is something like this 

   
                        xxxxxxx
Date
2004-12-31 | 13097.12
2005-01-31 | 13789.46

but if you check that same info on investing. com appears something like this
https://mx.investing.com/indices/ipc-historical-data

Ene 2005 | 13,097.12 
Feb 2005 | 13,789.46

so it appear to be a lag.

your api is awesome btw.

**Comment by alvarobartt** [comment]
Hi @manueldiazrod97! It's ok you don't bother me 🤗 

Could you provide a screenshot of the code and its output so that I can check it? I think that you want to retrieve the historical data from 2005 to 2020, but `investpy` is also retrieving data from the last day of 2004. am I right? Just let me know 👍🏻

**Comment by manueldiazrod97** [comment]
This is my code:
![Captura de Pantalla 2021-02-01 a la(s) 17 28 51](https://user-images.githubusercontent.com/60160380/106530967-f73f2900-64b2-11eb-85e2-318e0e771d4f.png)

This is the output:

![Captura de Pantalla 2021-02-01 a la(s) 17 29 23](https://user-images.githubusercontent.com/60160380/106531013-0920cc00-64b3-11eb-817a-a353ada0e37e.png)

this are  the results  from investing.com:

![Captura de Pantalla 2021-02-01 a la(s) 17 30 30](https://user-images.githubusercontent.com/60160380/106531098-31102f80-64b3-11eb-9a11-a4cab2f2374b.png)


the value from January 2005 is in December 2004

**Comment by alvarobartt** [comment]
Thanks for the detailed information @manueldiazrod97! I get what you mean with the 2004 date that should not be there, but regarding the rest of the dates, the output format is the last day of each month as when using the monthly interval, the months needs to be over so that Investing.com can put all the data together. So the format will remain the same, but I will check this 2004 issue, as AFAIK that date should not be in the returned `pandas.DataFrame` 👍🏻

**Comment by alvarobartt** [comment]
Hi again @manueldiazrod97! I've tested the function and this is what I get:

![imagen](https://user-images.githubusercontent.com/36760800/107118080-fa556300-687e-11eb-8407-e735b9121491.png)

I think the error may come when doing the conversion from `timestamp` to Date due to your region (which I think that it's from outside Europe) so the skew between our times is the issue why you are also receiving a skewed `pandas.DataFrame`, let me check it more in detail!

**Comment by alvarobartt** [comment]
As I'm using this line to do the conversion:

```python
index_date = datetime.strptime(str(datetime.fromtimestamp(int(info[0]), tz=pytz.utc).date()), '%Y-%m-%d')
```

I think I should use GMT conversion rather than UTC (Local time) conversion, let me modify it in the current branch and then you can install it as it follows from source. Then once you check that it also works from your country I'll generate the stable 1.0.2 release officially so that you can install it from PyPI rather than from source. 🤗 

```
pip install git+https://github.com/alvarobartt/investpy.git@master
```
