### ISSUE TITLE
DOT/Polkadot missing in crypto?

### ISSUE THREAD

**Issue by ymyke** [alvarobartt/investpy#302]
Thanks for the package!

DOT seems to be missing:

`investpy.crypto.get_cryptos().query("symbol == 'DOT'")`

Turns up nothing.

Any idea why it is missing and what I can do to fix this?

**Comment by alvarobartt** [comment]
Sure @ymyke I'll update the `crypto.csv` file for the next release, which will be `v1.0.4` hopefully later this week! 👍🏻

**Comment by Egoistically** [comment]
If anyone doesn't want to wait for the update for whatever reason, you can modify the `crypto.csv` file yourself.
The only "tricky" value is the id (int), which can be found by inspecting page source in the form of `pid-{id}-last` (inside `price js-currency-price`).

**Comment by alvarobartt** [comment]
Hi @ymyke and @Egoistically, the `cryptos.csv` static file is being updated right now, so it will be soon included in the `dev` branch. This means that you can either install `investpy` from that branch, or wait until the `v1.0.4` release comes out once merged.

I'll share with you the installation command once the file is updated! 🤗 (Expect this to be in an hour or less)

**Comment by alvarobartt** [comment]
Also note that there are a lot of missing cryptos in Investing.com, as some of them are listed but not available since Investing.com doesn't have access to the data. This means that you should double check whether Investing.com contains the cryptos you are looking for or not, as being listed in the `cryptos.csv` file doesn't mean they are available unless the `status` field is set to `available`.

An example on how to check this from Investing.com provided below:

![Screenshot from 2021-03-22 20-09-39](https://user-images.githubusercontent.com/36760800/112045712-7368fb00-8b4b-11eb-9028-3c38430b1786.png)

So that the highlighted ones with a link are available, but all the other ones are not.

**Comment by alvarobartt** [comment]
Already updated in the `dev` branch, soon available in the `v1.0.4` release :fire:

Install it from source as it follows:

``
pip install git+https://github.com/alvarobartt/investpy.git@dev
``

Remember to star the repository, follow me here and on Twitter at https://twitter.com/alvarobartt so as to get notified from all the updates and projects I'm working on! :star::octocat:
