### ISSUE TITLE
unidecode in get_fund_information makes fund naming inconsistent with funds in "funds" DataFrame

### ISSUE THREAD

**Issue by romanminkoff** [alvarobartt/investpy#313]
Reproducer: investpy.get_fund_information("öhman Global Growth", "sweden")
Error signature: ERR#0019: fund ohman global growth not found, check if it is correct.
investing.com link: https://www.investing.com/funds/ohman-global-growth-company-profile

Problematic lines in funds.py:
fund = unidecode(fund.strip().lower())  **# << here unidecode replaces "ö"->"o"**
if fund not in list(funds['name'].str.lower()):  **# << however funds DataFrame contains "öhman Global Growth" name (with original "ö")**
    raise RuntimeError("ERR#0019: fund " + fund + " not found, check if it is correct.")

Not sure if unidecode is really needed (default in python 3+). Majority of funds are not affected. Funds with "special characters" should probably keep original name for consistency reasons - and they do in funds DataFrame.

**Comment by alvarobartt** [comment]
Hi @romanminkoff, I get your point, but so as to make it simpler I just decided to "unidecode" everything so that you get the same information either introducing `öhman Global Growth` or `ohman Global Growth`, even though as you say, I may have messed up the static files so some cases those don't match! 😩 

Let me check this later today and then I'll release the fixed `investpy v1.0.4` release 🔥 Thanks for spotting this issue!

**Comment by romanminkoff** [comment]
Thank you!
