### ISSUE TITLE
ConnectionError: ERR#0015

### ISSUE THREAD

**Issue by coal2clean** [alvarobartt/investpy#369]
Hi! Thanks so much for providing this package. 

I was trying to query "Carbon Emissions" futures data but I constantly get this connection error. `ConnectionError: ERR#0015`

Its full_name="Carbon Emissions Futures"
https://www.investing.com/commodities/carbon-emissions

**Comment by mehmetayhantr** [comment]
I'm getting an ERR#0015 error too.

> ConnectionError: ERR#0015: error 503, try again later.

**Comment by alvarobartt** [comment]
Hi @coal2clean and @mehmetayhantr!

The error you are showing above is directly related to Investing.com (on the server-side) so I can't do anything about it since I'm not related at all with Investing.com so there's no way I can fix that... :weary:

It seems that Investing.com is failing these days but I don't know the reason yet!

Some other users reported this issue already during the last day or two... https://github.com/alvarobartt/investpy/issues/364

**Comment by alvarobartt** [comment]
I'm closing this now, even though I'll try to ask Investing.com the reason for these issues, and how long is this maintenance or unstable status going to take! :+1:
