### ISSUE TITLE
[QUESTION] is there a way to listen do economic calendar updates?

### ISSUE THREAD

**Issue by LeonardoRick** [alvarobartt/investpy#384]
I wish to have realtime updates on news but I don't want to call the API every minute. Is there a way to listen to all new updates that's comming?

**Comment by alvarobartt** [comment]
Hi @LeonardoRick I'm not sure you can do that even through the Investing.com website, since I've checked and it seems that there's no socket opened while querying the economic calendar... 😖 

So I think that you can just call the `investpy.economic_calendar()` function to get the updates... If you have any additional information or tips on how this could be done so as to avoid sending too many requests, please lmk!

Thank you! :+1:

**Comment by LeonardoRick** [comment]
Yes, I taught some socket could be opened. But if its not, I have no idea too. Thanks for answering!
