### ISSUE TITLE
Dumb Question, but where did you get the stock IDs from

### ISSUE THREAD

**Issue by bigboy32** [alvarobartt/investpy#385]
Hi,

Where did you get the stock ids from?

Thanks,
Anant

**Comment by alvarobartt** [comment]
Hi @bigboy32, not dumb at all mate! :+1: I got the IDs from the Investing.com site, since the metadata of the HTML contains those IDs so I just built some web scrapers to retrieve all the listed financial products in Investing.com, even though the Investing.com indexing is not that good and some products are missing in the listings provided, which means that you can just access them by querying the search engine!

So currently the CSVs are outdated and don't contain the complete information... but while I fix it (I proposed a solution in #374 so as to start deprecating the usage of static CSVs to look up for the IDs) you should use `investpy.search_quotes` since you will be using the Investing.com search engine rather than a lookup on the static CSV files, which means that the data returned by the function is always up to date and accessible 👍🏻 

I'll be closing this issue, since it's just a question, but for more information stay tuned and watch the issue I shared with you since I'll try to see whether the deprecation of the static files with the Investing.com search engine works as it should. :hugs:
