### ISSUE TITLE
Do you have minute data instead of day data?

### ISSUE THREAD

**Issue by sunrise1234321** [alvarobartt/investpy#461]
Thanks!!!!

**Comment by ReynardoEW** [comment]
I know that this issue is 23 days old and I probably should've made a new issue instead, but is it possible for us to fetch the data from the streaming chart? (which do have minute timeframe)

For example
https://www.investing.com/equities/bnk-central-as-chart
![image](https://user-images.githubusercontent.com/28998793/141677153-17ed05a2-1a40-443d-bf21-6110449f80ab.png)
![image](https://user-images.githubusercontent.com/28998793/141677158-06676375-c8de-4a9d-b06f-4fc08e106dc6.png)
![image](https://user-images.githubusercontent.com/28998793/141677166-26e1cedf-5847-42fa-abb8-6c5e830a4a7e.png)
