### ISSUE TITLE
Missing Mr D I Y Group M Bhd (MRDI)

### ISSUE THREAD

**Issue by mrkgoh** [alvarobartt/investpy#468]
Please note that the following ISIN MYL5296OO008 stock  is missing from investpy. 

This issue is pretty common. I know there is a static file that needs to be updated. Please provide guidance as to how to update the static file and I would happy to contribute in the future.

![Capture](https://user-images.githubusercontent.com/30623155/140030515-3168944e-ac2c-42c4-974b-d4fb64bb5fd9.JPG)

**Comment by alvarobartt** [comment]
Hi @mrkgoh, as you're saying, we have a huge issue with the static files that need to be updated, but that's something we're already working on! :muscle: Anyway, instead of updating the static files, which is a manual step, you can just use `investpy.search_quotes` function to look for any financial product as long as it's available at Investing.com.

Here's the [Official Documentation](https://investpy.readthedocs.io/_info/usage.html#search-live-data) and here's the [GitHub Wiki](https://github.com/alvarobartt/investpy/wiki/investpy.search_quotes()) for that, hope this helped you! If you have any other doubt or need an example just let me know and I'll be glad to answer :hugs:

**Comment by mrkgoh** [comment]
@alvarobartt thanks. I have hardcoded my script to use the search query alternative if the stock is not found. That's a temporary fix for now.
