### ISSUE TITLE
Date Index Off a Day

### ISSUE THREAD

**Issue by behanse** [alvarobartt/investpy#95]
Hello, 
When i run the same code 

investpy.get_stock_historical_data(stock='bbva',country='spain',from_date='01/01/2015',to_date='01/01/2019',as_json=False,order='ascending').tail()

I get the correct data but the date is one day behind (for example, the close on 12/31/2018 was 4.636, which is shown, however, the index date is 12/30/18). I have had the same issue on other tickers as well. 

Thanks!

**Comment by alvarob96** [comment]
Hi @behanse!

I tried the piece of code you presented above, and the error you are mentioning does not seem to be happening when I run the following code in Jupyter Notebooks:

![issue95](https://user-images.githubusercontent.com/36760800/72430794-863baf00-3793-11ea-9ea7-242354c0eb56.png)

Please, note that input dates are presented in *dd/mm/yyyy* format and that the returned `pandas.DataFrame` formats those dates as *yyyy-mm-dd* format since date strings are converted into `pandas.core.indexes.datetimes.DatetimeIndex` objects. Maybe the issue you are mentioning has something to do with that.

Anyways, for further advice, please make sure to paste also the code's output so that I can understand the issue better. Thank you for reporting it! Hope I could help you! :star: :octocat:

**Comment by behanse** [comment]
Hello and thanks for the quick reply, I appreciate it. You are doing great work. I wonder if the date conversion is causing an issue because here is the code and the output and I'm still getting everything one day off. 

![output](https://user-images.githubusercontent.com/32422145/72471801-9443fc80-37a0-11ea-8700-fed258f5886b.PNG)

**Comment by samcie** [comment]
I see the same issue... dates are off by one. I'm guessing this maybe a timezone issue as I am in the US and I believe the package was developed in/for Spain. This stack overflow post describes a similar issue. 

https://stackoverflow.com/questions/45150314/pandas-dataframe-dates-off-by-one-day

**Comment by eisimoes** [comment]
Check my comment on:

https://github.com/alvarobartt/investpy/issues/109#issuecomment-623622037

**Comment by alvarobartt** [comment]
Hi @behanse and @samcie, this issue has been properly solved as @eisimoes proposed. So thank you all for reporting and solving the issue, respectively.

__Note that currently it is just available on the developer version__ which you can install with the following command:
```
pip install git+https://github.com/alvarobartt/investpy.git@developer
```

__Thank you! Remember to star the repo if you found it useful and follow me at GitHub so as to get notified of all the updates!__
